### ISSUE TITLE
[Bug] error on Rule type route_db_from_data ,  value_on_unmatch not working

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/influxdb-srelay#11]
In the following configuration rule, the value_on_unmatch ( db will take the point if not match, the tag namespace) is not  working as it doesn't exist

````toml
     [[http.endpoint.route.rule]]
        name="to_namespace_metrics"
        action="route_db_from_data"
        key="tag"
        key_aux="namespace"
        match="(.*)"
        value="$1"
        value_on_unmatch="db_test_1"
        to_cluster="cluster_caas"
````
