### ISSUE TITLE
[Bug] queryRouterEndpointAPI not working, does not seem to be populated

### ISSUE THREAD

**Issue by akashgautam24** [toni-moreno/influxdb-srelay#22]
Hi, 

While trying to redirect /query to active endpoints, I see that it is always redirected to the first specified backend.

On this line [https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/cluster/influxcluster.go#L322](https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/cluster/influxcluster.go#L322),  
I see that the variable `queryRouterEndpointAPI` is an empty list, and does not seem to be populated anywhere. 

Could you please go through the code and explain how this variable works?

**Comment by toni-moreno** [comment]
Hi @akashgautam24 , in order to redirect over an active influxdb  you need configure a list of HTTP endpoints like this one:

https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/examples/rwha-sample.influxdb-srelay.conf#L53

Srelay expects  for each endpoint a list of active influxdb servers with its ID's in the influxdb-srelay.conf 

````bash
curl http://my_check_active_server:4090/api/queryactive
[
  "myinfluxdb01",
  "myinfluxdb02"
]
````

if more than one srelay will choose the first one.

This URL could be served by any HTTP server you want, or you can use if you need the syncflux tool (https://github.com/toni-moreno/syncflux) than has an  embedded active monitoring thread  for an HA cluster. If you choose syncflux remember use the same ID's for both config files.


You could build the HA server as in the next picture

![a](https://user-images.githubusercontent.com/5883405/55809639-9036d000-5ae6-11e9-90d2-3b1b6639ecc4.png)

**Comment by akashgautam24** [comment]
I did configure it according to the diagram shown as shown above (as shown in issue #9 as well),   
and I am able to curl my active syncflux instance on `/api/queryactive` to get the list of active backends, which gives me a list of 1 node.  

However, as I mentioned my `/query` api on srelay does not get redirected to that active node, and instead is directed to the first specified backend. 

To verify, I also tried looking up usages of `c.queryRouterEndpointAPI`, but I could not find anywhere where that array is being populated.

**Comment by toni-moreno** [comment]
did you named the influxdb instance ID's exactly equal in both tools ? Could you upload both config files?

**Comment by toni-moreno** [comment]
Hi @akashgautam24 did you fix your issue ?

**Comment by akashgautam24** [comment]
Hi @toni-moreno , 
I have not been able to fix my issue yet.

**influxdb-srelay1.conf**
```toml
###############################
##
## InfluxDB Single instances Config
##
###############################

# InfluxDB Backend InfluxDB01
[[influxdb]]
  name = "influxdb01"
  location = "http://172.16.3.18:8086/"
  timeout = "10s"

# InfluxDB Backend InfluxDB02
[[influxdb]]
  name = "influxdb02"
  location = "http://172.16.3.72:8086/"
  timeout = "10s"


#################################
##
## InfluxDB Cluster Configs as a set
## of influxdb Single Instances
##
#################################


# Cluster for linux Metrics
[[influxcluster]]
  # name = cluster id for route configs and logs
  name  = "ha_cluster"
  # members = array of influxdb backends
  members = ["influxdb01","influxdb02"]
  # where to write logs for all  operations in the cluster
  log-file = "ha_cluster.log"
  # log level could be
  # "panic","fatal","Error","warn","info","debug"
  log-level = "info"
  # mode = of query and send data
  # * HA :
  #       input write data will be sent to all members
  #       queries will be sent  on the active node with
  #       data if query-router-endpoint-api config exist, else the first
  # * Single:
  #       input write data will be sent on the first member ( should be only one)
  #     query will be sent on  the only first member (should be only one)
  # * LB:  // NOT IMPLEMENTED YET //
  type = "HA"
  # query-router-endpoint-api:
  #     List of API url which give us the name of the influxdb backend available with all available data (when recovery process)
  #     use any available sync tool as in https://github.com/toni-moreno/syncflux if needed
  #
  query-router-endpoint-api = ["http://172.16.3.18:4090/api/queryactive","http://172.16.3.72:4090/api/queryactive"]


# HTTP Server
[[http]]
  name = "ha-relay"
  bind-addr = "0.0.0.0:9096"
  log-file = "http_harelay_9096.log"
  log-level = "info"
  access-log = "ha_access.log"

  rate-limit = 1000000
  burst-limit = 2000000

  ## Define endpoints base config
  ## endpoints can have read and write properties

  ## Example: /query endpoint
  ## There are 2 routes that must do a read query  against a cluster
  ## It expects that each HTTP request tries each route. If it fits the filter it will be enrouted
  ## All requests that doesn't pass through  the filter tries the next route


  #
  # IQL /query Endpoint
  #
  [[http.endpoint]]
    uri=["/query"]
    # type
    #  * RD = http for query db
    #  * WR = http for send data to the db
    type="RD"
    # source_format
    # Supported formats
    # * ILP = influxdb-line-protocol
    # * prom-write = prometheus write format
    # * IQL = Influx Query Language
    source_format="IQL"

    ## READ request - linux_METRICS
    [[http.endpoint.route]]
      name="any_read"
      # level:
      #   * http => all following rules will work only with http params
      #   * data => any of the following rules will need data inspection
      level="http" # http or data
      # true => will use the endpoint log as this route log
      # false => will use its own log file ,  if not set the name <logdir>/http_route_<route_name>.log
      log-inherit = false
      #log-file = "query_route_linux_metrics.log"
      log-level = "info"

      ## Filter only the request with db param = linux_metrics
      [[http.endpoint.route.filter]]
        name="pass_all"
        #------------------------------------------------------------------------------------
        # Key for filter usage could be only at http level parameters (header/query)
        #  Header based
        #  -------------
        #    * authorization: Authorization Header
        #    * remote-address: Remote Address Header
        #    * referer: Referer Header
        #    * user-agent: User-Agent Header
        #  Query Based
        #  -------------
        #   (https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/)
        #   (https://docs.influxdata.com/influxdb/v1.7/tools/api/#write-http-endpoint)
        #    * db [r/w]: InfluxDB to read / Write
        #    * q [r]: InfluxQL query
        #    * epoch [r]: precision on read queries
        #    * precision [w] : precision on write queries
        #    * chunked [r]: (see referenced doc)
        #    * chunksize[r]: (see referenced doc)
        #    * pretty[r]:(see referenced doc)
        #    * u [r/w]: read/write user
        #    * p [r/w]: read/write password
        #    * rp[w]: retention policy
        #    * consistency[w]: (see referenced doc)
        #  Computed
        #    * username: computed from authorization header or u parameters
        # Key for Rule Usage (not this level) could be also data level parameters
        #   * measurement: match the measurement name
        #   * tag: match the tag value with tag key in key_aux
        #   * field: match the field value with field key in key_aux (always as string!!!! at this level)
        # ----------------------------------------------------------------------------------------------
        key="db" #availabe http params
        match=".*"

      ## Rule to route to cluster_linux
      [[http.endpoint.route.rule]]
        name="route_all"
        # Action Route
        #       * route:
        #       If key value (usually http level key) match with match parameter, The complete
        #       request will be sent to the cluster configured in to_cluster param
        #       Next rule step will have untouched data available for any other process
              #   * route_db_from_data (enable multitenancy)
        #       Will rename de db parameter depending for each point in data depending on
        #       the matching with one point parameter , by example one tag, enable write data
        #       to several databases (split data) from the same source.
        #       with this rule 1 HTTP request will become N HTTP request to our backends
        #       HTTP response will be logged without feedback with the original request
        #       Next rule step will have untouched data available for any other process
              #   * rename_http
              #   * rename_data
              #   * drop_data
        #   * break"
        action="route"
        # See
        key="db"
        match=".*"
        to_cluster="ha_cluster"

  [[http.endpoint]]
    uri=["/write"]
    source_format="ILP"
    type = "WR"

    ## WRITE request - windows
    [[http.endpoint.route]]
      name="any_write"
      level="http"

      [[http.endpoint.route.filter]]
        name="pass_all"
        key="db"
        match=".*"

      ## Send to PMEREASP15 cluster
      [[http.endpoint.route.rule]]
        name="route_all"
        action="route"
        key="db"
        match=".*"
        to_cluster="ha_cluster"
```

**influxdb-srelay2.conf**
```toml
###############################
##
## InfluxDB Single instances Config
##
###############################

# InfluxDB Backend InfluxDB01
[[influxdb]]
  name = "influxdb01"
  location = "http://172.16.3.18:8086/"
  timeout = "10s"

# InfluxDB Backend InfluxDB02
[[influxdb]]
  name = "influxdb02"
  location = "http://172.16.3.72:8086/"
  timeout = "10s"


#################################
##
## InfluxDB Cluster Configs as a set
## of influxdb Single Instances
##
#################################


# Cluster for linux Metrics
[[influxcluster]]
  # name = cluster id for route configs and logs
  name  = "ha_cluster"
  # members = array of influxdb backends
  members = ["influxdb01","influxdb02"]
  # where to write logs for all  operations in the cluster
  log-file = "ha_cluster.log"
  # log level could be
  # "panic","fatal","Error","warn","info","debug"
  log-level = "info"
  # mode = of query and send data
  # * HA :
  #       input write data will be sent to all members
  #       queries will be sent  on the active node with
  #       data if query-router-endpoint-api config exist, else the first
  # * Single:
  #       input write data will be sent on the first member ( should be only one)
  #     query will be sent on  the only first member (should be only one)
  # * LB:  // NOT IMPLEMENTED YET //
  type = "HA"
  # query-router-endpoint-api:
  #     List of API url which give us the name of the influxdb backend available with all available data (when recovery process)
  #     use any available sync tool as in https://github.com/toni-moreno/syncflux if needed
  #
  query-router-endpoint-api = ["http://172.16.3.72:4090/api/queryactive","http://172.16.3.18:4090/api/queryactive"]


# HTTP Server
[[http]]
  name = "ha-relay"
  bind-addr = "0.0.0.0:9096"
  log-file = "http_harelay_9096.log"
  log-level = "info"
  access-log = "ha_access.log"

  rate-limit = 1000000
  burst-limit = 2000000

  ## Define endpoints base config
  ## endpoints can have read and write properties

  ## Example: /query endpoint
  ## There are 2 routes that must do a read query  against a cluster
  ## It expects that each HTTP request tries each route. If it fits the filter it will be enrouted
  ## All requests that doesn't pass through  the filter tries the next route


  #
  # IQL /query Endpoint
  #
  [[http.endpoint]]
    uri=["/query"]
    # type
    #  * RD = http for query db
    #  * WR = http for send data to the db
    type="RD"
    # source_format
    # Supported formats
    # * ILP = influxdb-line-protocol
    # * prom-write = prometheus write format
    # * IQL = Influx Query Language
    source_format="IQL"

    ## READ request - linux_METRICS
    [[http.endpoint.route]]
      name="any_read"
      # level:
      #   * http => all following rules will work only with http params
      #   * data => any of the following rules will need data inspection
      level="http" # http or data
      # true => will use the endpoint log as this route log
      # false => will use its own log file ,  if not set the name <logdir>/http_route_<route_name>.log
      log-inherit = false
      #log-file = "query_route_linux_metrics.log"
      log-level = "info"

      ## Filter only the request with db param = linux_metrics
      [[http.endpoint.route.filter]]
        name="pass_all"
        #------------------------------------------------------------------------------------
        # Key for filter usage could be only at http level parameters (header/query)
        #  Header based
        #  -------------
        #    * authorization: Authorization Header
        #    * remote-address: Remote Address Header
        #    * referer: Referer Header
        #    * user-agent: User-Agent Header
        #  Query Based
        #  -------------
        #   (https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/)
        #   (https://docs.influxdata.com/influxdb/v1.7/tools/api/#write-http-endpoint)
        #    * db [r/w]: InfluxDB to read / Write
        #    * q [r]: InfluxQL query
        #    * epoch [r]: precision on read queries
        #    * precision [w] : precision on write queries
        #    * chunked [r]: (see referenced doc)
        #    * chunksize[r]: (see referenced doc)
        #    * pretty[r]:(see referenced doc)
        #    * u [r/w]: read/write user
        #    * p [r/w]: read/write password
        #    * rp[w]: retention policy
        #    * consistency[w]: (see referenced doc)
        #  Computed
        #    * username: computed from authorization header or u parameters
        # Key for Rule Usage (not this level) could be also data level parameters
        #   * measurement: match the measurement name
        #   * tag: match the tag value with tag key in key_aux
        #   * field: match the field value with field key in key_aux (always as string!!!! at this level)
        # ----------------------------------------------------------------------------------------------
        key="db" #availabe http params
        match=".*"

      ## Rule to route to cluster_linux
      [[http.endpoint.route.rule]]
        name="route_all"
        # Action Route
        #       * route:
        #       If key value (usually http level key) match with match parameter, The complete
        #       request will be sent to the cluster configured in to_cluster param
        #       Next rule step will have untouched data available for any other process
              #   * route_db_from_data (enable multitenancy)
        #       Will rename de db parameter depending for each point in data depending on
        #       the matching with one point parameter , by example one tag, enable write data
        #       to several databases (split data) from the same source.
        #       with this rule 1 HTTP request will become N HTTP request to our backends
        #       HTTP response will be logged without feedback with the original request
        #       Next rule step will have untouched data available for any other process
              #   * rename_http
              #   * rename_data
              #   * drop_data
        #   * break"
        action="route"
        # See
        key="db"
        match=".*"
        to_cluster="ha_cluster"

  [[http.endpoint]]
    uri=["/write"]
    source_format="ILP"
    type = "WR"

    ## WRITE request - windows
    [[http.endpoint.route]]
      name="any_write"
      level="http"

      [[http.endpoint.route.filter]]
        name="pass_all"
        key="db"
        match=".*"

      ## Send to PMEREASP15 cluster
      [[http.endpoint.route.rule]]
        name="route_all"
        action="route"
        key="db"
        match=".*"
        to_cluster="ha_cluster"
```


These are my config files; as can be seen,  the names of influxdb instances are same in both the files. 


I would once again request you to please explain me how the variable ```c.queryRouterEndpointAPI``` in 
https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/cluster/influxcluster.go#L322
gets populated, as I am unable to find where this array gets filled.

Thanks.
