### ISSUE TITLE
Duplicate information of cluster

### ISSUE THREAD

**Issue by zhangxin511** [toni-moreno/influxdb-srelay#9]
The [influxcluster](https://github.com/toni-moreno/influxdb-srelay/blob/master/examples/rwha-sample.influxdb-srelay.conf#L38-L48)  in rwha-sample.influxdb-srelay.cong seems duplicated info with [query-router-endpoint-api](https://github.com/toni-moreno/influxdb-srelay/blob/master/examples/rwha-sample.influxdb-srelay.conf#L53)?

For the SyncFlux, we can run as a HA Cluster, with 1 master 1 slave.

My question is:
1. Do we still need to define the cluster information again in srelay? 
2. Current implementation of SyncFlux, the HA cluster can have two DB Backend one master one slave. can it have more slaves?
3. I am not quite understand the current example [rwha-sample.influxdb-srelay.conf](https://github.com/toni-moreno/influxdb-srelay/blob/master/examples/rwha-sample.influxdb-srelay.conf), say I have two DB Backends running, one on localhost:8086 one on localhost:8087. We can define two `[[influxdb]]`, but the example show we can also define two endpoints in `query-router-endpoint-api`, which is the cluster endpoint of SyncFlux. My understanding is we can only have one SyncFlux cluster by the existing two db.
4. Also I am not quite understand how `hamonitor` of `SyncFlux` works. I tested to write data when one node is down (either master or slave), but I don't see data was synced.

**Comment by toni-moreno** [comment]
Hi @zhangxin511 , you should keep in mind the proposed architecture layout.


![HA_architecture_with_syncflux](https://user-images.githubusercontent.com/5883405/55809639-9036d000-5ae6-11e9-90d2-3b1b6639ecc4.png)

As you could see , there are:

* 2 influxdb-srelay instances
* 2 syncflux instances
 
Working on both nodes 

In this layout with the dbbackend names in influxdb-srelay.conf and the influxdb  name  in the syncflux.conf shoud be the same.

Supose the  rwha-sample. influxdb-srelay.conf 

### influxdb-srelay.conf ( in myinfluxdb01_server ) 

````toml
...
...
[[influxdb]]
  name = "myinfluxdb01"
  location = "http://myinfluxdb01_server:8086/"
  timeout = "10s"


[[influxdb]]
  name = "myinfluxdb02"
  location = "http://myinfluxdb02_server:8086/"
  timeout = "10s"

[[influxcluster]]
  # name = cluster id for route configs and logs
  name  = "ha_cluster"
  # members = array of influxdb backends
  members = ["myinfluxdb01","myinfluxdb02"]
  log-file = "ha_cluster.log"
  log-level = "info"
  type = "HA"
  query-router-endpoint-api = ["http://myinfluxdb01_server:4090/api/queryactive","http://myinfluxdb02_server:4090/api/queryactive"]
..
...
````

### influxdb-srelay.conf ( in myinfluxdb02_server ) 

````toml
...
...
[[influxdb]]
  name = "myinfluxdb01"
  location = "http://myinfluxdb01_server:8086/"
  timeout = "10s"


[[influxdb]]
  name = "myinfluxdb02"
  location = "http://myinfluxdb02_server:8086/"
  timeout = "10s"

[[influxcluster]]
  # name = cluster id for route configs and logs
  name  = "ha_cluster"
  # members = array of influxdb backends
  members = ["myinfluxdb02","myinfluxdb01"] 
  log-file = "ha_cluster.log"
  log-level = "info"
  type = "HA"
  query-router-endpoint-api = ["http://myinfluxdb02_server:4090/api/queryactive","http://myinfluxdb01_server:4090/api/queryactive"]
...
...
````
Only changes the members and query-router-endpoint-api  order to query first its own syncflux

### syncflux.conf  (on myinfluxdb01_server )

```toml
 master-db = "myinfluxdb01"
 slave-db = "myinfluxdb02"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb01"
 location = "http://myinfluxdb01_server:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb02"
 location = "http://myinfluxdb02_server:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"
````

### syncflux.conf  (on myinfluxdb02_server )

Only  swaps mater and slave values

```toml
 master-db = "myinfluxdb02"
 slave-db = "myinfluxdb01"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb01"
 location = "http://myinfluxdb01_server:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb02"
 location = "http://myinfluxdb02_server:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"
````

About your questions:

1)  As in the previous example  ( let me know if more doubts on that issue)
2) Right now , there is no way to have more than one (as  this one is also a very young project) , but if needed won't be difficult to add this feature.
3,4)  Config as in the layout and example. If you have more questions about how to config and possible errors please open and specific issue in the https://github.com/toni-moreno/syncflux issue manager.

I hope you can understand how smart-relay and syncflux can work together to build a better HA solution when we can not run a  InfluxDB Enterprise  cluster.

Any other question?

**Comment by zhangxin511** [comment]
Appreciated for you detailed info. I tried your approach, since I am not sure where the HA load Balance coming from I made only one srelay instance but keeps the others as you suggested, but still can't make data in sync when one node is down. 
This is what I have done:

1. `docker-compose up`
2. `curl -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"`
3. `curl -XPOST http://localhost:8087/query --data-urlencode "q=CREATE DATABASE mydb"` (haven't try to turn on the admin on influx to use your admin endpoint)
4. Baseline, `curl -i -XPOST "http://127.0.0.1:9096/write?db=mydb" --data-binary "cpu_load_short,host=server01,region=us-west value=0.64 1434055561000000000"`, both database backend got the data `2015-06-11T20:46:01Z server01 us-west 0.64`
5. stop influx-a(running on 8086), `docker-compose stop influx-a`
6. Try insert data while a is down, `curl -i -XPOST "http://127.0.0.1:9096/write?db=mydb" --data-binary "cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000"`, which is `2015-06-11T20:46:02Z server01 us-west 0.64`
7. Start influx-a again `docker-compose start influx-a`
8. Wait, then check database, the `2015-06-11T20:46:02Z server01 us-west 0.64` never synced back to a, while b have the two data entries.

Here is my setup:

docker-compose.yml
```
version: '3.7'
services:
  influx-a:
    image: influxdb:1.7
    ports:
      - 8086:8086
    volumes:
      - C:/Docker/InfluxHA/Influxdb/a:/var/lib/influxdb
  influx-b:
    image: influxdb:1.7
    ports: 
      - 8087:8086
    volumes:
      - C:/Docker/InfluxHA/Influxdb/b:/var/lib/influxdb
  influx-relay:
    image: tonimoreno/influxdb-srelay:latest
    ports:
      - 9096:9096
    links:
      - influx-a
      - influx-b
      - sync-flux-a
      - sync-flux-b
    volumes:
      - C:/Docker/InfluxHA/Influx-srelay/conf/influxdb-srelay.conf:/etc/influxdb-srelay/influxdb-srelay.conf
      - C:/Docker/InfluxHA/Influx-srelay/log/:/var/log/
  sync-flux-a:
    image: tonimoreno/syncflux
    ports:
      - 4090:4090
    links:
      - influx-a
      - influx-b
    volumes:
      - C:/Docker/InfluxHA/Sync-flux/a/conf/:/opt/syncflux/conf/
      - C:/Docker/InfluxHA/Sync-flux/a/log/:/opt/syncflux/log/
  sync-flux-b:
    image: tonimoreno/syncflux
    ports:
      - 4091:4090
    links:
      - influx-a
      - influx-b
    volumes:
      - C:/Docker/InfluxHA/Sync-flux/b/conf/:/opt/syncflux/conf/
      - C:/Docker/InfluxHA/Sync-flux/b/log/:/opt/syncflux/log/  
```
The configuration file and folder structure are attached. I am sorry to bother you like this, but could you take a look and let me know what went wrong? Much appreciated!
[InfluxHA.zip](https://github.com/toni-moreno/influxdb-srelay/files/3212999/InfluxHA.zip)

**Comment by toni-moreno** [comment]
Hi @zhangxin511  I will check your config  ASAP

**Comment by toni-moreno** [comment]
Hi @zhangxin511 first thing I've detected is in your syncflux.toml config.

db names  should be the same in both engines srelay and syncflux config

#### influxdb-srelay.conf 
````toml
  [[influxdb]]
    name = "myinfluxdb01"
    location = "http://influx-a:8086/"
    timeout = "10s"
  
  [[influxdb]]
    name = "myinfluxdb02"
    location = "http://influx-b:8086/"
    timeout = "10s"

````

#### syncflux-a.toml 

````toml
master-db = "myinfluxdb01"
slave-db = "myinfluxdb02"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb01"
 location = "http://influx-a:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb02"
 location = "http://influx-b:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"
````

#### syncflux-b.toml 

````toml
master-db = "myinfluxdb02"
slave-db = "myinfluxdb01"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb01"
 location = "http://influx-a:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"

[[influxdb]]
 release = "1x"
 name = "myinfluxdb02"
 location = "http://influx-b:8086/"
 admin-user = "admin"
 admin-passwd = "admin"
 timeout = "10s"
````

Could you fix these config files and test again please?
